apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-seq
spec:
  completions: 5
  template:
    metadata:
      name: batch-job-seq
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job
